[[redirects]]
  from = "/symbols"
  to = "https://github.com/aritropaul/SFSymbolPicker"
  status = 302
  force = true
  headers = {X-From = "aritro.work"}


[[redirects]]
  from = "/widget"
  to = "https://github.com/aritropaul/WidgetKit-Example"
  status = 302
  force = true
  headers = {X-From = "aritro.work"}

[[redirects]]
  from = "/widgetpost"
  to = "https://aritro.me/blog/2020/06/Writing-A-SwiftUI-Widget.html"
  status = 302
  force = true
  headers = {X-From = "aritro.work"}